### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by mdj2812** [mdj2812/stm32f4-discovery#3]
# To do
- [ ] Plug in the Parking Sensor
- [ ] Some basic commandes towards smart sensors (e.g. Power down, Power up, synchronization...)
# Next
- [ ] Make it work with Raspberry
- [ ] Establish a server with the raspberry
- [ ] Using Raspberry to arrange the data received and upload them to the database
